spring:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor?useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
